title: "My Org Blog"
description: "A Jekyll blog built from Org files"
url: "https://rvf0068.github.io"
baseurl: "/jekyll-org-pandoc"
theme: minima

markdown: kramdown

# Exclude org files from Jekyll processing since they're converted to markdown
exclude:
  - "*.org"
  - "_posts/*.org"
